### ISSUE TITLE
Add .nvmrc file to fix development node version

### ISSUE THREAD

**Issue by Minhir** [igorkamyshev/farfetched#103]
Currently, 18 node is not supported by Cloudflare:

https://github.com/igorkamyshev/farfetched/pull/101
https://github.com/cloudflare/pages-build-image/discussions/1

So we need to wait Cloudflare image update, and after we can add `.nvmrc` file

**Comment by igorkamyshev** [comment]
So, I think, Couldflare cannot make our life easier in this case, so I set up GitHub Action instead — https://github.com/igorkamyshev/farfetched/commit/f3f6ceadd13c6495828653f8326827e2c853ae13
