### ISSUE TITLE
Typescript compiles with an error when pass effector's store to `headers`

### ISSUE THREAD

**Issue by a-polunin** [igorkamyshev/farfetched#145]
Hello!
I use `createJsonQuery` and have headers which are effector's `Store`. I want to pass them to the request, but I get a typescript error `Type 'FetchApiRecord' is not assignable to type '{ Authorization: string; }'.` But it's wrong. Header's type is compatible to [FetchApiRecord](https://github.com/igorkamyshev/farfetched/blob/master/packages/core/src/misc/fetch_api.ts#L1)

```
const $headers = createStore({
  Authorization: `Bearer jwt`
});

const query = createJsonQuery({
  request: {
    method: 'GET',
    url: url,
    headers: $headers
  },
});
```
There is a simple workaround. But anyway, it would be nice if there were less unexpected errors :)
```
headers: {
     source: $headers,
     fn: (_, headers) => headers
},
```
I've created a [sandbox](https://codesandbox.io/s/suspicious-rain-q9ti4y?file=/src/index.ts), so you can check it out there 🙂 

Thank you, lib is great!

**Comment by igorkamyshev** [comment]
Thanks for report. As I understand, it could be solved only after https://github.com/effector/effector/issues/722

I've marked it as blocked for now 🤗
