### ISSUE TITLE
Add `nullContract` to check response is `null` (empty)

### ISSUE THREAD

**Issue by blackwhite2018** [igorkamyshev/farfetched#240]
Setting Null, Void, Optional from runtypes doesn't help. MB you can try to register a custom contract.

**Comment by igorkamyshev** [comment]
Hello! Thanks for report 🙏

I've tried to reproduce your report (https://github.com/igorkamyshev/farfetched/pull/242/files), but didn't succeed. Could you provide some repro?

**Comment by igorkamyshev** [comment]
Probably it is the same problem there — https://codesandbox.io/s/dry-dawn-ryfyl7?file=/src/index.ts

**Comment by igorkamyshev** [comment]
It is probably fixed in 0.7.2, can you check?

**Comment by igorkamyshev** [comment]
I assume it's fixed 🤗
