### ISSUE TITLE
Proposal: extend the isHttpErrorCode API

### ISSUE THREAD

**Issue by StanislavMyakishev** [igorkamyshev/farfetched#261]
Hi! 
When you use isHttpErrorCode helper as a utility to filter retries condition you sometimes have conditions like 'filter all 50x errors' or 'filter all 40x errors'. With the interface of isHttpErrorCode being just a numeric parameter of error to check it turns out to be a large sequence of code
```typescript
return isHttpErrorCode(500)(error) || isHttpErrorCode(501)(error) || ...
```

My proposal is to add some variety to the code parameter so it can be used like 
```typescript
return isHttpErrorCode([500, 501, 502, 503])(error)
```

or even 
```typescript
return isHttpErrorCode('50x')(error)
```

**Comment by igorkamyshev** [comment]
Done, will be released in #312
