### ISSUE TITLE
Typing error for types declared via an interface

### ISSUE THREAD

**Issue by abakimatov** [igorkamyshev/farfetched#266]
Hi, I've encountered a typing bug. If we pass the type described through the interface as a generic to the `declareParams` when declaring a mutation through the `createJsonMutation`, we get an error. If you change the spelling of the type through type alias, the error disappears and the types are displayed as they should.

[Reproduce](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAbzgYygUwIYzQKQM4QB2AsgK4xbBEA0cAJmsgDYboAKrGIecAvnADMoEEHADkAAQGsBaGMgAWaOgHpk0NGIDcAKFCRYiOFFKEYATzBoAwkRhQMyePyEjxUmXMXKVJs5bQ8bT1waHgkVExsAGUYDT5BYVExNAFZJ2gxEINwuAAlRmg6BNdkvwsrIJ0ddUI8eAASdRAQIgBFUjQocw4HbjgAXhR0LDRYjQAKBAEICAAucQAjVjFeAEoaonq4BqUMBigeIcjR8fQpgEFyBWhgAC9KIgWxVY3NuvgAdWAYBToHADuBTwpCYMAAInFBvlClA6FN1tVgGYutJkGg4L0uDwEDo4MY0ABHTr1ZQAfWQGDwCmWyAA1gtcfj8chSFB0IRkOYKRAGAt6lBkQBzXTMuAANwwTE6C0IpBAiy6or4yvQxMC2DoPIATIy8cywMJxcADvz7MLlSy2RyuTy+XABRb9fjJdK0LL5YqoMreMqwBhzCA0GYyRV3YhnXAw89loQ6RTWHRgmLXTKI2KWYmyXKFV0zYLCCLI5m4WSbkxTQ7zYXLSrI3gMOLw4tZkxMIQfbpfdVatsAT8-oCyBQYFRCNCTth8ERh49CFN9f6+ngFgxmKw0FjuAAeLd4AB8EzW1H1apJMD1YrZTGeKn7v3+GABYlocEjQd+vOebAA8tEACovpGLZ0OYCwTEu2JrIM+5wJB3AnmK6rdJeGYEGy6ILE0IitIQHRdD0nAIcWgiEOBZK0MhhHLtBAywVRe6IcyvBMfiewHCu6ZoRAGHhrsmAcaxzICGRcATBRcDsV0eC0bBUmHEJLH6kp+LoHgkB1OGTLMrU9iOBeximGGthmA4TgTN8D6AsCoIQnEx7KSe6xaEAA) in typescript playground

Code examples:
![image](https://user-images.githubusercontent.com/30955537/218391802-b3becb74-9968-4e71-8d54-8e0969b98fe6.png)

![image](https://user-images.githubusercontent.com/30955537/218391861-64239a39-b6f5-4e0e-9fbe-107d5bce8ad8.png)

**Comment by igorkamyshev** [comment]
Thanks for the report, I've written a test for this case — https://github.com/igorkamyshev/farfetched/pull/267. I'll fix it asap 🤗

**Comment by abakimatov** [comment]
Thank you so much 💙

**Comment by igorkamyshev** [comment]
So, it is some TS internal magic, I've failed to find any documentation of it. My advice — just use type aliases for this case 🥲

**Comment by igorkamyshev** [comment]
Sorry 😥

**Comment by igorkamyshev** [comment]
So, @yumauri asked this question on SO and got an answer — https://stackoverflow.com/questions/55814516/typescript-why-type-alias-satisfies-a-constraint-but-same-interface-doesnt
