### ISSUE TITLE
Ability to skip intermediate events during retries

### ISSUE THREAD

**Issue by abakimatov** [igorkamyshev/farfetched#273]
In some cases, it may be necessary to subscribe only to the last request completion event. For example, depending on the state of the request, we show a spinner in the UI. When the request completes, we will hide the spinner and either show a data screen or show an error message. In this case, we are not interested in the events of an unsuccessful request, if there will be another attempt after it. It is important for us to know only the result of the whole operation. I would like to be able to skip intermediate events when adding retrays for Query. 🙏

**Comment by igorkamyshev** [comment]
Sounds legit 🤔 let's collect more real world uses cases before implementing

**Comment by igorkamyshev** [comment]
Yeah, it has to be done. I assume, something like this 👇
```
retry(query, {
  supressIntermidiateErrors: true
})
```

(naming could be improved)

Let's plan it for 0.9, because it requires kinda design and I do not want to postpone 0.8 for this minor change.

**Comment by igorkamyshev** [comment]
Will be released in v0.9
