### ISSUE TITLE
Add support for Domains

### ISSUE THREAD

**Issue by vsviridov** [igorkamyshev/farfetched#279]
Currently one can't pass a domain to the FarFetched functions, but it could be useful.

For example, in my existing fetching logic based on Effects I was doing the following to have an "in-flight" request counter
```ts
export const domain = createDomain('apiDomain');

export const $inFlightRequests = createStore(0, { domain });

export const $requestsPending = $inFlightRequests.map(x => x > 0);

domain.onCreateEffect(fx => {
  $inFlightRequests.on(fx, x => x + 1).on(fx.finally, x => x - 1);
});
```

Later on the effects in the API slice all use this domain and I have a store that shows if there are currently pending requests, so I can drive UI overlays based on that, for example.

I can also wire up failed requests to a Toast, for instance, without having to replicate the functionality in each API request.

I could probably achieve it by using a custom factory, but for something very simple it's a lot of boilerplate.

**Comment by igorkamyshev** [comment]
Actually, I did not catch it. What's the point in using domains for this purpose?

With domains:
```ts
const trackingDomain = createDomain()

const q1 = createQuery({
  domain: trackingDomain
})

const q2 = createQuery({
  domain: trackingDomain
})
```

without domains:

```ts
const trackQuery = (q) => {/*...*/}

const q1 = createQuery()
trackQuery(q1)

const q2 = createQuery()
trackQuery(q2)
```

For me, the second example more explicit and composable, and it has the same size as the first one.

Would this approach solve your case?

**Comment by igorkamyshev** [comment]
So, Effector's ecosystem is moving away from domains concept. I assume, we should not add it to Farfetched.

https://withease.pages.dev/magazine/no_domains.html
