### ISSUE TITLE
Add ability to mock network error and bad status codes

### ISSUE THREAD

**Issue by abakimatov** [igorkamyshev/farfetched#282]
When testing models that can respond to various request termination options (including unsuccessful scenarios) it is useful to be able to mock the result of a network error, 4XX and 5XX status codes, etc.

**Comment by igorkamyshev** [comment]
Sure, fetchFx should be exposed. Will be done in 0.8

**Comment by igorkamyshev** [comment]
Done in https://github.com/igorkamyshev/farfetched/commit/2f6fa1c59f3e1c726a4770577178f0cc724359e9, will be released in 0.8
