### ISSUE TITLE
Each start of query creates copy of the same key in the `__farfetched_meta__` (LS cache)

### ISSUE THREAD

**Issue by dzhiriki** [igorkamyshev/farfetched#288]
Reproduce: https://stackblitz.com/edit/effector-vite-react-template-qtvvtg

After a couple of clicks on «Refresh» you will have
```json
{
  "keys": [  
    "f5523ce8fa505f3d8b78afb108c8ae24c8475d5b",
    "f5523ce8fa505f3d8b78afb108c8ae24c8475d5b",
    "f5523ce8fa505f3d8b78afb108c8ae24c8475d5b",
    "f5523ce8fa505f3d8b78afb108c8ae24c8475d5b"
  ]
}
```
in `__farfetched_meta__` in LS

**Comment by igorkamyshev** [comment]
Fixed in https://github.com/igorkamyshev/farfetched/commit/4c7f25f63816a44b793b19c2a7de7c1187d33650, will be released in 0.8.1
