### ISSUE TITLE
Farfetched errors are plain objects

### ISSUE THREAD

**Issue by vsviridov** [igorkamyshev/farfetched#293]
Using farfetched API's with SolidJS causes some issues, as SolidJS re-wraps any caught errors that are not `instanceof Error` into a new instance of `Error`, which causes it to lose message and stack trace, and makes reacting to them that much more difficult.

https://github.com/solidjs/solid/blob/main/packages/solid/src/reactive/signal.ts#L1705

**Comment by igorkamyshev** [comment]
Thanks for report 🫶 I'll think about it and fix ASAP

**Comment by igorkamyshev** [comment]
I see, this change was [introduced in SolidJS 1.5](https://github.com/solidjs/solid/pull/1176), so before we did not have this problem. Will be fixed in 0.8.3.
