### ISSUE TITLE
boolean fields in params

### ISSUE THREAD

**Issue by dontmeway** [igorkamyshev/farfetched#299]
[ts-playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQKQM4QB2AigK5pQCeANHACZrIA2G6ACqxiHnAL5wAzKBBBwA5AAEBrAWhjIAFmjoB6ZNDRiAUKEixEcKKUIxKYNAGEiMKBmTx+QkeKky5i5SqMmzaPNt1oeCQAJUZoOloAZRtgQgBzPkFhUTFvU3N-LS11Qjx4UigmOABeOAAKYDoALjh8qDj4gEpSgD44AAMVMCwFFQASBCreDuzc-LgAR3IqUpR0LFwCEhnKcoQtOC24HttuWoZmVjQOPbwAHiGautiE2icQWsJSEAAjCloYCCeX96haEDWBRMSi1V4QCBMTCEXitcpNaibbboaZ+GC1DbbLFwQpMWrrYYtErtXGVOgIpHYuAgOQKCDXMQAcQAogAVMSIqlbVFUfEIB6fCAAoEg3hE9rrAVwL7CkzAyhiyl8TnIvyQPJoDFKrG5Gx2dGGYwZSzWWz2cphdRQOgE64xBoJMVNJW8LSK7JbIA)

**Comment by igorkamyshev** [comment]
Thanks for report 🫶

Fixed https://github.com/igorkamyshev/farfetched/commit/8bf8b772e78fe37b29a8788ee6b97ef63716776d and will be released 0.8.4 in an hour.
