### ISSUE TITLE
abortible request as separate status

### ISSUE THREAD

**Issue by slavanchikus** [igorkamyshev/farfetched#300]
if request is aborted, query.$status value is _failed_
can you create new status, like _aborted_ for this case?

**Comment by igorkamyshev** [comment]
The first step (adding Event `.aborted`) is done and will be released in #312. Complete migration will be finished in v0.10 since we cannot change library behavior without prior warning.

**Comment by igorkamyshev** [comment]
Done in https://github.com/igorkamyshev/farfetched/pull/357, will be released in 0.10
