### ISSUE TITLE
Unable to import `createAdapter` function from @farfetched/core

### ISSUE THREAD

**Issue by lenstr** [igorkamyshev/farfetched#303]
Hi! It seems like `createAdapter` function is not exported in `packages/core/index.ts`, but acording to documentation it should be https://farfetched.pages.dev/recipes/server_cache.html#implementation

**Comment by igorkamyshev** [comment]
Hello! Thanks for report. I assume, it's a bug. I'll fix it in the next release 🤗

**Comment by igorkamyshev** [comment]
Exposed as `createCacheAdapter` in 0.8.6 ✅
