### ISSUE TITLE
Add not required concurrency param for `createQuery`

### ISSUE THREAD

**Issue by dmitryshelomanov** [igorkamyshev/farfetched#309]
You need to add the _concurrency_ parameter to apply request cancellation strategies. Useful if the api layer is not json api (for example: grpc, sockets)

**Comment by igorkamyshev** [comment]
I'm going to exclude this from v0.9 release because it's better to wait https://github.com/effector/effector/pull/931 instead of introducing workarounds. Thay tuned 💙

**Comment by igorkamyshev** [comment]
@AlexandrHoroshih proposed stack-based solution for the original issue. So, will be done in v0.10.

**Comment by igorkamyshev** [comment]
Sorry, have to postpone to 0.12

**Comment by igorkamyshev** [comment]
Done in https://github.com/igorkamyshev/farfetched/pull/440
