### ISSUE TITLE
`CacheAdapter` type is not exported

### ISSUE THREAD

**Issue by yumauri** [igorkamyshev/farfetched#319]
```ts
import type { CacheAdapter } from '@farfetched/core'
```

Complains:
```
Module '"@farfetched/core"' declares 'CacheAdapter' locally, but it is not exported.(2459)
```

I understand that TypeScript could infer type from `createCacheAdapter` function, but there are cases, when it is required to define return type for function, for example, eslint rule [`explicit-function-return-type`](https://typescript-eslint.io/rules/explicit-function-return-type) or [`explicit-module-boundary-types`](https://typescript-eslint.io/rules/explicit-module-boundary-types).

In that case user have to write ad hoc solution like

```ts
function redisCache(options: { maxAge: number }): ReturnType<typeof createCacheAdapter>
```

or define own type like

```ts
type CacheAdapter = ReturnType<typeof createCacheAdapter>
function redisCache(options: { maxAge: number }): CacheAdapter
```

Both looks ugly IMO, while library could just export this type, with zero extra cost.

**Comment by igorkamyshev** [comment]
Thanks for report 🫶 done in https://github.com/igorkamyshev/farfetched/commit/528416b906094788a4b17cf3a389b1bee991d434, will be released in 0.8.11
