### ISSUE TITLE
pending is written before data

### ISSUE THREAD

**Issue by blackwhite2018** [igorkamyshev/farfetched#325]
https://stackblitz.com/edit/effector-react-nbpnyk?file=src%2Fapplication.tsx

**Comment by igorkamyshev** [comment]
It is considered as a bug in Effector. Will be fixed in the next major release (around July 6th) — https://github.com/effector/effector/pull/916

**Comment by igorkamyshev** [comment]
Since Farfetched cannot fix it, and it is considered as a bug in Effector, let me close this issue for now 😇
