### ISSUE TITLE
Incorrect attachOperation behavior

### ISSUE THREAD

**Issue by limkaa4** [igorkamyshev/farfetched#327]
[code](https://codesandbox.io/s/condescending-sound-mr7lsd?file=/src/index.ts)

Expected behavior:
firstQuery should be called with url - https://jsonplaceholder.typicode.com/posts?searchTerm=searchTerm
lastQuery should be called with url - https://jsonplaceholder.typicode.com/posts?userIds=1,2,3,4,5

Current behavior:
firstQuery called with url -https://jsonplaceholder.typicode.com/posts?userIds=1,2,3,4,5
lastQuery called with url - https://jsonplaceholder.typicode.com/posts?userIds=1,2,3,4,5

**Comment by igorkamyshev** [comment]
I've found a bug and added test-case. It'll be fixed in the release v0.9.

**Comment by igorkamyshev** [comment]
Done, will be released in v0.9
