### ISSUE TITLE
implement type checking on pending and error to throw data null type exception

### ISSUE THREAD

**Issue by YockyMai** [igorkamyshev/farfetched#334]
when checking the pending and error status options, data can still be of type null, although the check completely excludes this option.
![image](https://github.com/igorkamyshev/farfetched/assets/75245399/add6013c-b247-45ac-b302-5b7cffd0b75f)

**Comment by igorkamyshev** [comment]
Actually, I have no idea how to provide this level of type checks. As I know, it's impossible in TS.

Do you know how to do it?

**Comment by igorkamyshev** [comment]
After some research, I am convinced that it is impossible in the current version of TS.
