### ISSUE TITLE
[Feature Request] Add `$finished` derived store to Remote Operations (Query, Mutation)

### ISSUE THREAD

**Issue by risen228** [igorkamyshev/farfetched#342]
In some cases, we need to obtain a Store indicating that the Query is completed.

Essentially, this is a computed value based on two states: `'done'` and `'fail'`:

```
const $finished = or(query.$succeeded, query.$failed)
```

I encountered a situation where in multiple places, the Query array is mapped to stores, which should take this status into account. Due to the dynamic generation through the `map` function, it is not possible to declare such a store at a higher level. So, I have to either duplicate this logic or create a small factory like `finished(query)`. Both options are not very convenient, and it would be great to have such a computed Store directly within the Query structure.

**Comment by igorkamyshev** [comment]
Done, will be released in v0.9
