### ISSUE TITLE
Add info about status code for `success` event

### ISSUE THREAD

**Issue by pnkll** [igorkamyshev/farfetched#343]
I am using `createQuery/createMutation` and I would like to get `statusCode` information when I subscribe to finished.success. It seems now it is possible to process such a case by passing `status.expected` to the query creation parameters, but then it will be necessary to create several `Query` and process them separately. It would be convenient if there was an opportunity to get information about the status in `finished.success` in the same way as now we have in `finished.failure`

**Comment by igorkamyshev** [comment]
Hello! Yeah, sounds great.

**Comment by igorkamyshev** [comment]
I believe it's a same issue as https://github.com/igorkamyshev/farfetched/issues/286. Let's close this one and track progress in https://github.com/igorkamyshev/farfetched/issues/286.
