### ISSUE TITLE
Allow optional parameters in query field 

### ISSUE THREAD

**Issue by StanislavMyakishev** [igorkamyshev/farfetched#345]
The `query`  in createJsonQuery is now allowing only parameters without any optional fields. But sometimes I need to use the following params type like so

```typescript
type TQueryParams = {
  type: TType;
  optional_id?: number;
  with_some_mode?: boolean;
};
```

To pass those to the query field I came up with the helper function

```typescript
const filterEmptyParams = (
  params: Record<string, Partial<unknown>>,
): Record<string, string> => {
  return Object.entries(params).reduce((acc, [key, value]) => {
    if (value === undefined) return acc;
    return { ...acc, [key]: String(value) };
  }, {});
};
```

But I think that optional parameters should be allowed, it would be nice 🤗

**Comment by igorkamyshev** [comment]
Done, will be released in v0.10
