### ISSUE TITLE
`update` types error

### ISSUE THREAD

**Issue by dontmeway** [igorkamyshev/farfetched#370]
Even if the `initialData` was passed to the `query`, you still need to write `typeguard` in `update` operator.

[typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQUQGZ5rLwC+ceUEIcA5GgUTNDQFCiSyKqbYCKArmigBPADQp0WNAFl+MLMAgA7cfzAATKWQpVaAATwYohGMgAWadQHpk0NKxYtbSgM7wAjoJEAxAB5wAXgkeXAZiAB4ANwhgdXElfhAAIyEAbQBdAD4ACgBKJ2U3OBA5BWU-QOCpfEIIhOSheMSUqBz8x2cizyFhSu4pAR7shBY4Mbh6WpgALjhun19RUfHgJWAYYAwAGwARLAxZjKWSds74EvkN5T7JbFlLxSVh5bHJxlmLsqU-Y-aWNU02Gy8zEiBecGUH1KVxU4KSwlmI3GyLgLn4yGQaBcLlmw0+MPEIJOgUycGeKIpcHQaK2MzgqQAdEyQQzqfxaeJ8Y9WVj2TB0uDkSdwSQWCcgA)

**Comment by igorkamyshev** [comment]
Thanks for the report, I'll fix it in the next release

**Comment by igorkamyshev** [comment]
Done, will be released in 0.10.1 today 😇
