### ISSUE TITLE
Add new Statement: No globals

### ISSUE THREAD

**Issue by NazariiShvets** [igorkamyshev/farfetched#380]
## Proposal
It would be great to have global hook to attach custom logic to each query

## Usecase: Monitoring contract mismatch
It would be very usefull to collect metrics for contract mismatches and send it to some external system, so it would be easy to track and fix all related issues

Something like this:
```
import { isInvalidDataError, onQueryCreated } from '@farfetched/core'
 
onQueryCreated(query => {
  sample({
    clock: query.finished.failed,
    filter: isInvalidDataError,
    fn: mapToCustomMonitoringFormat,
    target: $$monitoring.captureErrorFx
  })
})
```

**Comment by igorkamyshev** [comment]
Hello! Farfetched does not support any globals.

So, I suggest to use something like this for this use-case:
```ts
function monitorFailedContract(query) {
  sample({
    clock: query.finished.failed,
    filter: isInvalidDataError,
    fn: mapToCustomMonitoringFormat,
    target: $$monitoring.captureErrorFx
  })
}

monitorFailedContract(myQuery1)
monitorFailedContract(myQuery2)
```

It is a mistake that this idea is not covered in the Statements sections of the docs. Let me rename this issue and close it after adding a new statement.

**Comment by NazariiShvets** [comment]
@igorkamyshev So custom query factories is the way to go, if i want to gradually upgrade my queries with new common logic? I should not expect `hooks` like or `queryClient` provided by farfeched?

**Comment by igorkamyshev** [comment]
> @igorkamyshev So custom query factories is the way to go, if i want to gradually upgrade my queries with new common logic? I should not expect `hooks` or `queryClient` provided by farfeched? 

Yes.
