### ISSUE TITLE
TypeError: params.valueOf is not a function

### ISSUE THREAD

**Issue by NazariiShvets** [igorkamyshev/farfetched#385]
While integrating `@farfetched/atomic-router` my chained routes randomly stopped opening

Further investigation of that points to `isEqual` call inside `sample.fn` which throws errors therefore breaking execution https://github.com/igorkamyshev/farfetched/blob/3ec5631e37fa03b402bcd08a93d6de2fb49ffc06/packages/core/src/query/create_headless_query.ts#L170

As result, chainRoute stuck

Sometimes it can be reproduced with
```
const a = {};
a.__proto__ = null;
a.valueOf() // TypeError
```
but not all the time. 

For now I doen't have time to spend to provide exhaustive reproduce. Will come back to this with 100% reproduce
Just wanted to let u know about it. 

Meanwhile fixed this with 
<img width="567" alt="image" src="https://github.com/igorkamyshev/farfetched/assets/74127809/0abffcd5-e863-4410-b589-daaa61af6a01">

**Comment by igorkamyshev** [comment]
Wow 😮 thanks for the report, I'll take a look

**Comment by igorkamyshev** [comment]
Release 0.10.3 contains fixes for this issue ✅
