### ISSUE TITLE
How to debug sha1 keys?

### ISSUE THREAD

**Issue by NazariiShvets** [igorkamyshev/farfetched#393]
It very hard to debug combination from which items in cache were added because `sha1` is **Secure** hash algorithm so it's practicly imposible to reverse result of that hash function

And it is a problem, because all API provided (Observability API) is based on result of `createKey` aka `sha1`. And I can't derive from that key any meaningful information (i`m looking for combination of params + sourced fields 
)

I guess reasoning behind this is to dont have a problem with long keys from library point

So the question is:
 - Can we switch to using human-readable cache keys? (like react-query does with https://github.com/TanStack/query/blob/8906dac48847404c9ab84fd975052f70062048d7/packages/query-core/src/utils.ts#L180)

 - Maybe we can support custom hash functions, so for enviroments, where length of key is not a real constrain, (`inMemoryAdapter`) we could have human-readable cache keys? (https://github.com/TanStack/query/blob/8906dac48847404c9ab84fd975052f70062048d7/packages/query-core/src/utils.ts#L172)

**Comment by igorkamyshev** [comment]
Great idea. Will be done in the next minor release, with something like this 👇
```ts
cache(query, {
  humanReadableKeys: true,
})
```

Naming could be improved.

**Comment by igorkamyshev** [comment]
It's done https://github.com/igorkamyshev/farfetched/pull/413/commits/b9d84bb72f0618c728e3de1bb9eed6d63cdaec9b and will be released in 0.12
