### ISSUE TITLE
Query/Mutation usage as effect

### ISSUE THREAD

**Issue by NazariiShvets** [igorkamyshev/farfetched#394]
I`m trying to integrate with third-party library, which expects from me Promise to load/update data

I`w seen [closed issue](https://github.com/igorkamyshev/farfetched/issues/237) about this, with reasoning:

> Farfetched build around the idea of queries connection

But in my case, its not about loading a lot of dependent queries to show data on page when its loaded
Its more about leveraging `retry` `update` `cache` `timeout` `contract` APIs for single query/mutation

Especially `update` bcs I don't see any way to update query data on event call. `update` only allows mutations

### Personal research
I`we tried to making my own implementation for this leveraging @farfetched/atomic-router integration
But it doesn't work with parallel calls
https://gist.github.com/NazariiShvets/29808a88648f23e7ef2e02eac936b210

### Possible solutions
 1. This approach will work, if there would be a way to pass some kind of meta to `query.start` and `query.refresh` and able to get it from `query.finished.*` with same reference
 
 So it would be possible to create some sort of `call-id` and compare it afterward, in `ExecutionMeta` for example.
 So this id could be created on user-side and passed direclty to `startWithMeta` which could be exposed behind `query.__.startWithMeta`
 
 2. Another aproach could be leveraging `callObj`, which already has `call-Id ` so it would be possible to differentiate different requests and resolve promises in the right way
  But the problem here is race conditions, bcs `callObj` resolves before `finished.*` events called. And probably doen't even called if there is cached data
  
  3. Rewrite execution part of ff so `start` and `refresh` would be `Effect<QueryParams, QueryData>`
    But it would be practicly impossible at this point

**Comment by NazariiShvets** [comment]
Also, it would be great selling point to gradually migrate from bare effects to farfetched queries

I assume, that most high level API would expect effect instead of 3 events, as it has more built-in features and easily extensible

**Comment by igorkamyshev** [comment]
I do not see why we have to reduce RemoteOperation to Effect.

For instance, Remote Operation have Event `.aborted`. How you are going to translate it to Effects?

**Comment by igorkamyshev** [comment]
Since there is no answer for now, let me close this issue. If you find a way to solve this design issue, please reopen it.
