### ISSUE TITLE
Proper `Accept` header should be provided in `createJsonQuery`

### ISSUE THREAD

**Issue by AlexandrHoroshih** [igorkamyshev/farfetched#399]
## Background

Currently `createJsonQuery` adds `Content-Type: application/json` to every request (except for GET and HEAD, obviosly) to mark the type of `body` content:
https://github.com/igorkamyshev/farfetched/blob/7432c75508576431ce3f7b676a6c53d65edced96/packages/core/src/fetch/json.ts#L46

## Suggestion

But `createJsonQuery` also **expects** JSON in response, so, probably, if there is no hidden pitfalls - there should be `Accept: application/json` header added to every request, something like this 🤔 

```ts
    ({ method, headers }) =>
     // reversed merge order
     // to allow any modifications in the user code
      mergeRecords({
        'Accept': 'application/json',
        'Content-Type': ['GET', 'HEAD'].includes(method!) ? undefined : 'application/json'
      }, headers)
```

**Comment by igorkamyshev** [comment]
Fixed in https://github.com/igorkamyshev/farfetched/commit/a3b87b675659eb5402df18e9126acdcb16aa637e and will be released as 0.10.6
