### ISSUE TITLE
Unexpected behaviour of  $status and $pending

### ISSUE THREAD

**Issue by Merciful12** [igorkamyshev/farfetched#410]
### Summary
Calling `query.start()` multiple times leads to unexpected behaviour of  `$status` and `$pending` with `TAKE_LATEST` strategy.

### Steps to reproduce
- go to https://codesandbox.io/p/devbox/quizzical-bohr-xxl72n
- open console
- quickly press a few buttons

### Expected behaviour
[Log] status – "pending"
[Log] pending – true

[Log] pending – false
[Log] status – "done"
[Log] data – {...}

### Actual behaviour
[Log] status – "pending"
[Log] pending – true

[Log] status – "initial"
[Log] pending – false

[Log] status – "done"
[Log] data – {...}

**Comment by igorkamyshev** [comment]
Thanks for the report. It's fixed in 0.11.1
