### ISSUE TITLE
`CacheAdapter.__.$instance` should be `StoreWritable`

### ISSUE THREAD

**Issue by victordidenko** [igorkamyshev/farfetched#439]
In order to work with `fork`, like described here:
https://farfetched.pages.dev/recipes/cache.html#adapter-replacement

https://github.com/igorkamyshev/farfetched/blob/74c291fc1395a0c47192bbab1174c9a43edb5b6f/packages/core/src/cache/adapters/type.ts#L25

**Comment by igorkamyshev** [comment]
Fixed in https://github.com/igorkamyshev/farfetched/commit/f14f944ffdf78eac248b932b46e7c9bb3d70538a and will be released 0.11.4
