### ISSUE TITLE
Typing connectQuery() function without fn argument (simplify form)

### ISSUE THREAD

**Issue by JustyDev** [igorkamyshev/farfetched#443]
Documentation screen:

<img width="811" alt="image" src="https://github.com/igorkamyshev/farfetched/assets/61616100/429af7dd-cda5-42da-b60a-26f00a18ff91">

That form typing is not working.

My code:

```js
import { connectQuery, createQuery } from '@farfetched/core'
import { query } from '@/app/lib/query'

export const refPageQuery = createQuery({
  name: 'refPageQuery',
  handler: async () => await fetch()
})

export const createRefQuery = createQuery({
  name: 'createRefQuery',
  handler: async () => await fetch()
})

//is not working
connectQuery({
  source: createRefQuery,
  target: refPageQuery,
})

//working
connectQuery({
  source: createRefQuery,
  fn() {
    return { params: {} }
  },
  target: refPageQuery
})
```

Error:

<img width="631" alt="image" src="https://github.com/igorkamyshev/farfetched/assets/61616100/58ac7ff5-5ec6-4e7a-b5f6-eb148beb0424">

<img width="465" alt="image" src="https://github.com/igorkamyshev/farfetched/assets/61616100/f70ec1dd-ceb5-4213-b374-f26193211b2f">

I hope you fix it)

**Comment by igorkamyshev** [comment]
Thanks for report 🙏

Fixed in https://github.com/igorkamyshev/farfetched/commit/1677023dbca82225b94197c7ff2a4f273c7715c7 and will be relased soon.
