### ISSUE TITLE
Added reset event to unitshape protocol

### ISSUE THREAD

**Issue by dmitryshelomanov** [igorkamyshev/farfetched#448]
[They](https://github.com/igorkamyshev/farfetched/blob/91f1f3c0fce57a3169785643c52d3f664008a425/packages/core/src/mutation/create_headless_mutation.ts#L63) forgot to add an reset event

**Comment by igorkamyshev** [comment]
Fixed in https://github.com/igorkamyshev/farfetched/commit/ce4ea66764652342761ce1d523139f3f31aa68f6 and will be released soon.
