### ISSUE TITLE
Add filter to connectQuery

### ISSUE THREAD

**Issue by usmanyunusov** [igorkamyshev/farfetched#462]
Есть возможность для connectQuery  добавить filter. Кейс когда только для авторизованного  пользователя запускать цепочку запросов.

**Comment by igorkamyshev** [comment]
Так оно есть 🤔 

https://farfetched.pages.dev/api/operators/connect_query.html

<img width="712" alt="Screenshot 2024-04-03 at 20 50 06" src="https://github.com/igorkamyshev/farfetched/assets/26767722/96887b72-35d3-49ef-b9a2-63fef7a62d6b">

**Comment by usmanyunusov** [comment]
@igorkamyshev Сори, не увидел. Спасибо.
