### ISSUE TITLE
Replace sha1 hash with simpler algorithm

### ISSUE THREAD

**Issue by zerobias** [igorkamyshev/farfetched#489]
[Sha1 implementation](https://github.com/igorkamyshev/farfetched/blob/ded5b2974e1be432ed39852e69f27789b3d1f01d/packages/core/src/cache/lib/hash.ts#L1) in farfetched is _very_ large and probably not so fast. We don't need cryptography-grade implementation for that case, so we can pick much simpler implementation from effector/babel-plugin:

```ts
function hashCode(s: string) {
  let h = 0
  let i = 0
  while (i < s.length) h = ((h << 5) - h + s.charCodeAt(i++)) | 0
  return h.toString(36)
}
```

It's came from java and battle-tested in effector itself

**Comment by igorkamyshev** [comment]
Done https://github.com/igorkamyshev/farfetched/commit/88b6096d7f61d8010c2da359cbe99b3760887387
