### ISSUE TITLE
Использование относительных URL в запросах

### ISSUE THREAD

**Issue by kirill-kalinin** [igorkamyshev/farfetched#493]
После обновления перестали работать запросы к API в приложениях, как выяснилось, проблема в том, что в новых версиях относительные URL считаются не валидными

Хотелось бы продолжить использовать относительные URL, кроме того, было бы здорово видеть ошибки, которые прерывают запрос, в консоли, потому что сейчас запросы просто молча не отправлялись, довольно долго пришлось разбираться, что вообще происходит

**Comment by igorkamyshev** [comment]
Поддержку относительных урлов вернул в https://github.com/igorkamyshev/farfetched/pull/494, сегодня будет в релизе.

Логирование ошибок в консоль — хорошая идея, добавлю в дев-тулзы в рамках https://github.com/igorkamyshev/farfetched/pull/482
