### ISSUE TITLE
API Documentation Error in Barrier

### ISSUE THREAD

**Issue by Rastraponovich** [igorkamyshev/farfetched#502]
Hello, method isHttpError not expected int.

[link](https://ff.effector.dev/api/factories/create_barrier.html) in documentation

<img width="760" alt="image" src="https://github.com/user-attachments/assets/f461bf68-a283-45fe-a762-860fce3f693c">

<img width="864" alt="image" src="https://github.com/user-attachments/assets/484c2dce-ee59-457d-99dc-5630f24bb481">

**Comment by igorkamyshev** [comment]
Thanks, fixed — https://github.com/igorkamyshev/farfetched/commit/4bed3da6e12a8bdb1559ec76dd18b9caa09386c4
