### ISSUE TITLE
Trigger API

### ISSUE THREAD

**Issue by yumauri** [igorkamyshev/farfetched#69]
Following [this comment](https://github.com/igorkamyshev/farfetched/issues/50#issuecomment-1235428126).

This is not an _issue_, but I was just curious about this use case, and how it could potentially be solved with farfetched.

For example, we have page with 5 widgets, each one fetches data, so, we have 5 data requests. All data available only for authenticated user. User logs into application, doing their things, then went to have lunch. After an hour they come back and wants to check data on those widgets. Clicks on a navigation link, page is opened, 5 requests are sent, but OH NO, authentication session has been expired, and all 5 requests have received error 401.

There was a requirement in one of my previous projects, so this is not some fancy user case out of nowhere. And the requirement was following:
- All 5 widgets continue to show "loading state"
- Sign-in form pops up, like modal window in overlay
- When user types their username and password and hits enter, sign-in form closes
- And all 5 widgets shows actual data

So, we need to postpone all failed requests somewhere in a internal queue, without showing errors to user, and without notifying widgets, that their requests has received responses (so they will continue to show "loading state" like still waiting for response). Then, after session successfully renewed — take all postponed failed requests out of the internal queue and retry them all. Upon receiving successful  responses widgets will show data. Like nothing happen. From each widget's point of view it was just a loooooong answer for the request. Widgets have no idea, that requests were actually failed and retried.

I'm pretty sure this could be implemented differently, but this is like I did this, literally. It was long ago, I was young, and it was angular.js though :) Maybe you will suggest different approach to implement this kind of requirement.

It could be other cases, like with tokens. For example:
Request receives error 401 in response. This means access token has been expired. We took refresh token, and requests new access token. Upon receiving new access token — retry failed request. All automated and without letting UI to even know there was some trouble.

**Comment by igorkamyshev** [comment]
I've read your case one more time and released that it would be covered by [Trigger API](https://farfetched.pages.dev/roadmap.html#v-0-8). I do not close this issue for now because I do not have clear vision of Trigger API, only general idea of executing Queries after some application-wide events.

Thanks, one more time 💙

**Comment by igorkamyshev** [comment]
related to #182

**Comment by NazariiShvets** [comment]
OTP Confirmation

I have a dynamic config for requests which needs cover by extra auth (MFA)

How it works: 
  1. Request sent
  2. Got specific HTTP error (eg. 'OTP_REQUIRED')
  3. Need to show prompt with OTP field to the user
  4. User types code
  5. Request retries with a new header
  
Note: 
  - OTPGuard can be on every request. And I don't want to check it manually every time
  - I don`t know which route has this guard. Completely dynamic, and can be changed in runtime (on the backend side)
